#!/usr/bin/env node
/**
 * BATCH 3 — High-traffic "how much" / "what is" calculators
 * These target question-based searches (huge Google volume)
 */
const fs = require('fs');
const AD = 'ca-pub-3112605892426625';
const BASE = 'https://calcleap.com';

if (!fs.existsSync(__dirname + '/calc')) fs.mkdirSync(__dirname + '/calc');

function calcPage(slug, title, desc, keywords, calcHTML, calcJS) {
    return `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>${title} — Free Online | CalcLeap</title>
<meta name="description" content="${desc}">
<meta name="keywords" content="${keywords}">
<link rel="canonical" href="${BASE}/calc/${slug}.html">
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${AD}" crossorigin="anonymous"></script>
<script type="application/ld+json">{"@context":"https://schema.org","@type":"WebApplication","name":"${title}","description":"${desc}","url":"${BASE}/calc/${slug}.html","applicationCategory":"UtilityApplication","operatingSystem":"Any","offers":{"@type":"Offer","price":"0","priceCurrency":"USD"}}</script>
<style>:root{--bg:#0a0e1a;--s:#111827;--s2:#1f2937;--b:#374151;--t:#f3f4f6;--m:#9ca3af;--a:#6366f1;--a2:#4f46e5;--g:rgba(99,102,241,.12)}*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:var(--bg);color:var(--t);line-height:1.6}header{background:var(--s);border-bottom:1px solid var(--b);padding:.75rem 1.5rem;position:sticky;top:0;z-index:100}.hi{max-width:800px;margin:0 auto;display:flex;align-items:center;gap:1rem}.logo{font-size:1.2rem;font-weight:800;color:var(--a);text-decoration:none}.tag{color:var(--m);font-size:.8rem;flex:1}main{max-width:800px;margin:0 auto;padding:2rem 1.5rem}h1{font-size:1.6rem;margin-bottom:.5rem}.sub{color:var(--m);margin-bottom:1.5rem;font-size:.9rem}.calc{background:var(--s);border:1px solid var(--b);border-radius:12px;padding:1.5rem}.field{margin-bottom:1rem}.label{display:block;font-weight:600;margin-bottom:.4rem;font-size:.85rem}input[type="number"],input[type="text"],input[type="date"],select,textarea{width:100%;padding:.7rem .9rem;background:var(--s2);border:1px solid var(--b);border-radius:8px;color:var(--t);font-size:.9rem;outline:none;font-family:inherit}input:focus,select:focus{border-color:var(--a);box-shadow:0 0 0 3px var(--g)}.row{display:grid;grid-template-columns:1fr 1fr;gap:.75rem}.row3{display:grid;grid-template-columns:1fr 1fr 1fr;gap:.75rem}.btn{padding:.65rem 1.2rem;background:var(--a);color:#fff;border:none;border-radius:8px;font-size:.9rem;font-weight:600;cursor:pointer}.btn:hover{background:var(--a2)}.result{margin-top:1.5rem;padding:1.5rem;background:var(--s2);border-radius:10px;text-align:center}.result .val{font-size:2rem;font-weight:800;color:var(--a)}.result .lbl{font-size:.8rem;color:var(--m);margin-top:.25rem}.results-grid{margin-top:1.5rem;display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:.75rem}.stat{background:var(--s2);border-radius:8px;padding:.75rem;text-align:center}.stat .val{font-size:1.2rem;font-weight:800;color:var(--a)}.stat .lbl{font-size:.7rem;color:var(--m)}.ad{max-width:800px;margin:1rem auto;padding:0 1.5rem}footer{text-align:center;padding:1.5rem;color:var(--m);font-size:.8rem;border-top:1px solid var(--b);margin-top:2rem}footer a{color:var(--a);text-decoration:none}table{width:100%;border-collapse:collapse;font-size:.85rem;margin-top:1rem}th,td{padding:.5rem .6rem;text-align:right;border-bottom:1px solid var(--b)}th{color:var(--m);font-weight:600;font-size:.7rem;text-transform:uppercase}td:first-child,th:first-child{text-align:left}@media(max-width:600px){.row,.row3{grid-template-columns:1fr}.results-grid{grid-template-columns:1fr 1fr}}</style>
</head><body>
<header><div class="hi"><a href="../index.html" class="logo">🔧 CalcLeap</a><span class="tag">Free Online Tools</span></div></header>
<div class="ad"><ins class="adsbygoogle" style="display:block" data-ad-client="${AD}" data-ad-slot="auto" data-ad-format="auto" data-full-width-responsive="true"></ins><script>(adsbygoogle=window.adsbygoogle||[]).push({});</script></div>
<main><h1>${title}</h1><p class="sub">${desc}</p><div class="calc">${calcHTML}</div></main>
<div class="ad"><ins class="adsbygoogle" style="display:block" data-ad-client="${AD}" data-ad-slot="auto" data-ad-format="auto" data-full-width-responsive="true"></ins><script>(adsbygoogle=window.adsbygoogle||[]).push({});</script></div>
<footer><a href="../index.html">CalcLeap</a> · <a href="https://alexchalu.github.io/smartcalc/">SmartCalc</a> · <a href="../blog/">Blog</a></footer>
<script>const $=id=>document.getElementById(id);const fmt=(n,d=2)=>typeof n==='number'?n.toLocaleString('en-US',{maximumFractionDigits:d}):'—';${calcJS}
if(typeof calc==='function')calc();</script></body></html>`;
}

const calcs = [
    { slug:'compound-interest', title:'Compound Interest Calculator', desc:'Calculate compound interest with monthly contributions. See how your money grows over time with detailed charts.',
      keywords:'compound interest calculator, interest calculator, savings calculator, investment growth, compound interest formula',
      html:`<div class="row"><div class="field"><label class="label">Initial Investment ($)</label><input type="number" id="principal" value="10000"></div><div class="field"><label class="label">Monthly Contribution ($)</label><input type="number" id="monthly" value="500"></div></div>
<div class="row"><div class="field"><label class="label">Annual Interest Rate (%)</label><input type="number" id="rate" value="7" step="0.1"></div><div class="field"><label class="label">Years</label><input type="number" id="years" value="20"></div></div>
<div class="field"><label class="label">Compound Frequency</label><select id="freq"><option value="12" selected>Monthly</option><option value="4">Quarterly</option><option value="1">Annually</option><option value="365">Daily</option></select></div>
<button class="btn" onclick="calc()">Calculate</button><div class="results-grid" id="out"></div><div id="table"></div>`,
      js:`function calc(){const P=+$('principal').value,m=+$('monthly').value,r=+$('rate').value/100,y=+$('years').value,n=+$('freq').value;let balance=P;const totalContrib=P+m*12*y;let rows='<table><tr><th>Year</th><th>Contributions</th><th>Interest</th><th>Balance</th></tr>';for(let yr=1;yr<=y;yr++){for(let i=0;i<12;i++){balance+=m;balance*=(1+r/n)}const contrib=P+m*12*yr;const interest=balance-contrib;rows+='<tr><td>'+yr+'</td><td>$'+fmt(contrib,0)+'</td><td>$'+fmt(interest,0)+'</td><td>$'+fmt(balance,0)+'</td></tr>'}rows+='</table>';const totalInterest=balance-totalContrib;$('out').innerHTML='<div class="stat"><div class="val" style="font-size:1.5rem;color:#22c55e">$'+fmt(balance,0)+'</div><div class="lbl">Final Balance</div></div><div class="stat"><div class="val">$'+fmt(totalContrib,0)+'</div><div class="lbl">Total Contributions</div></div><div class="stat"><div class="val">$'+fmt(totalInterest,0)+'</div><div class="lbl">Total Interest Earned</div></div><div class="stat"><div class="val">'+fmt(totalInterest/totalContrib*100,0)+'%</div><div class="lbl">Interest/Contributions</div></div>';$('table').innerHTML=rows}`
    },
    { slug:'inflation-calculator', title:'Inflation Calculator', desc:'Calculate the impact of inflation on purchasing power. See what your money will be worth in the future.',
      keywords:'inflation calculator, purchasing power, future value of money, inflation rate, cost of living',
      html:`<div class="row"><div class="field"><label class="label">Amount ($)</label><input type="number" id="amount" value="100000"></div><div class="field"><label class="label">Inflation Rate (%)</label><input type="number" id="rate" value="3" step="0.1"></div></div>
<div class="field"><label class="label">Number of Years</label><input type="number" id="years" value="10"></div>
<button class="btn" onclick="calc()">Calculate</button><div class="results-grid" id="out"></div><div id="table"></div>`,
      js:`function calc(){const a=+$('amount').value,r=+$('rate').value/100,y=+$('years').value;const future=a*Math.pow(1+r,y);const purchasing=a/Math.pow(1+r,y);const lost=a-purchasing;$('out').innerHTML='<div class="stat"><div class="val" style="color:#ef4444">$'+fmt(purchasing,0)+'</div><div class="lbl">Purchasing Power in '+y+' Years</div></div><div class="stat"><div class="val">$'+fmt(lost,0)+'</div><div class="lbl">Value Lost to Inflation</div></div><div class="stat"><div class="val">$'+fmt(future,0)+'</div><div class="lbl">Cost of $'+fmt(a,0)+' Item in '+y+' Years</div></div><div class="stat"><div class="val">'+fmt(lost/a*100,1)+'%</div><div class="lbl">Purchasing Power Lost</div></div>';let t='<table><tr><th>Year</th><th>Purchasing Power</th><th>Equivalent Cost</th><th>Lost Value</th></tr>';for(let i=1;i<=y;i++){const pp=a/Math.pow(1+r,i);t+='<tr><td>'+i+'</td><td>$'+fmt(pp,0)+'</td><td>$'+fmt(a*Math.pow(1+r,i),0)+'</td><td>$'+fmt(a-pp,0)+'</td></tr>'}t+='</table>';$('table').innerHTML=t}`
    },
    { slug:'retirement-calculator', title:'Retirement Calculator', desc:'Calculate how much you need to save for retirement. See if you are on track to retire comfortably.',
      keywords:'retirement calculator, retirement savings, how much to retire, retirement planning, 401k calculator',
      html:`<div class="row"><div class="field"><label class="label">Current Age</label><input type="number" id="age" value="30"></div><div class="field"><label class="label">Retirement Age</label><input type="number" id="retAge" value="65"></div></div>
<div class="row"><div class="field"><label class="label">Current Savings ($)</label><input type="number" id="savings" value="50000"></div><div class="field"><label class="label">Monthly Contribution ($)</label><input type="number" id="monthly" value="1000"></div></div>
<div class="row"><div class="field"><label class="label">Expected Return (%)</label><input type="number" id="returnRate" value="7" step="0.1"></div><div class="field"><label class="label">Desired Annual Income ($)</label><input type="number" id="income" value="80000"></div></div>
<button class="btn" onclick="calc()">Calculate</button><div class="results-grid" id="out"></div>`,
      js:`function calc(){const age=+$('age').value,ret=+$('retAge').value,sav=+$('savings').value,m=+$('monthly').value,r=+$('returnRate').value/100,inc=+$('income').value;const years=ret-age;let balance=sav;for(let i=0;i<years*12;i++){balance=balance*(1+r/12)+m}const needed=inc*25;const gap=needed-balance;const onTrack=balance>=needed;$('out').innerHTML='<div class="stat"><div class="val" style="font-size:1.5rem;color:'+(onTrack?'#22c55e':'#ef4444')+'">$'+fmt(balance,0)+'</div><div class="lbl">Projected at Retirement</div></div><div class="stat"><div class="val">$'+fmt(needed,0)+'</div><div class="lbl">Target Needed (25x Rule)</div></div><div class="stat"><div class="val" style="color:'+(onTrack?'#22c55e':'#ef4444')+'">'+(onTrack?'✅ On Track':'⚠️ $'+fmt(gap,0)+' Short')+'</div><div class="lbl">Status</div></div><div class="stat"><div class="val">'+years+' yrs</div><div class="lbl">Years to Retirement</div></div><div class="stat"><div class="val">$'+fmt(m*12*years+sav,0)+'</div><div class="lbl">Total Contributions</div></div><div class="stat"><div class="val">$'+fmt(balance-(m*12*years+sav),0)+'</div><div class="lbl">Interest Earned</div></div>'}`
    },
    { slug:'debt-to-income', title:'Debt-to-Income Ratio Calculator', desc:'Calculate your DTI ratio. Lenders use this to determine mortgage and loan eligibility.',
      keywords:'debt to income ratio, DTI calculator, mortgage qualification, loan eligibility, debt ratio',
      html:`<div class="field"><label class="label">Monthly Gross Income ($)</label><input type="number" id="income" value="7000"></div>
<p class="label" style="margin-top:1rem;margin-bottom:.5rem">Monthly Debt Payments:</p>
<div class="row"><div class="field"><label class="label">Mortgage/Rent ($)</label><input type="number" id="mortgage" value="1800"></div><div class="field"><label class="label">Car Payment ($)</label><input type="number" id="car" value="450"></div></div>
<div class="row"><div class="field"><label class="label">Student Loans ($)</label><input type="number" id="student" value="300"></div><div class="field"><label class="label">Credit Cards (min) ($)</label><input type="number" id="cc" value="150"></div></div>
<div class="field"><label class="label">Other Debt Payments ($)</label><input type="number" id="other" value="0"></div>
<button class="btn" onclick="calc()">Calculate DTI</button><div class="results-grid" id="out"></div>`,
      js:`function calc(){const inc=+$('income').value;const debt=+$('mortgage').value+ +$('car').value+ +$('student').value+ +$('cc').value+ +$('other').value;const dti=debt/inc*100;const rating=dti<=36?'🟢 Excellent':dti<=43?'🟡 Acceptable':dti<=50?'🟠 High':'🔴 Very High';const mortgage=dti<=36?'✅ Likely qualified':dti<=43?'⚠️ May qualify':'❌ Unlikely to qualify';$('out').innerHTML='<div class="stat"><div class="val" style="font-size:2rem;color:'+(dti<=36?'#22c55e':dti<=43?'#eab308':'#ef4444')+'">'+fmt(dti,1)+'%</div><div class="lbl">Debt-to-Income Ratio</div></div><div class="stat"><div class="val">'+rating+'</div><div class="lbl">Rating</div></div><div class="stat"><div class="val">'+mortgage+'</div><div class="lbl">Mortgage Eligibility</div></div><div class="stat"><div class="val">$'+fmt(debt)+'</div><div class="lbl">Total Monthly Debt</div></div><div class="stat"><div class="val">$'+fmt(inc-debt)+'</div><div class="lbl">Remaining Income</div></div><div class="stat"><div class="val">$'+fmt((inc*0.36)-debt)+'</div><div class="lbl">Room for More Debt (36%)</div></div>'}`
    },
    { slug:'car-loan-calculator', title:'Car Loan Calculator', desc:'Calculate monthly car payments, total interest, and compare loan terms for new and used auto loans.',
      keywords:'car loan calculator, auto loan calculator, car payment calculator, vehicle financing, car loan interest',
      html:`<div class="row"><div class="field"><label class="label">Vehicle Price ($)</label><input type="number" id="price" value="35000"></div><div class="field"><label class="label">Down Payment ($)</label><input type="number" id="down" value="5000"></div></div>
<div class="row"><div class="field"><label class="label">Interest Rate (%)</label><input type="number" id="rate" value="5.9" step="0.1"></div><div class="field"><label class="label">Loan Term</label><select id="term"><option value="36">36 months</option><option value="48">48 months</option><option value="60" selected>60 months</option><option value="72">72 months</option><option value="84">84 months</option></select></div></div>
<div class="field"><label class="label">Trade-in Value ($)</label><input type="number" id="trade" value="0"></div>
<button class="btn" onclick="calc()">Calculate</button><div class="results-grid" id="out"></div>`,
      js:`function calc(){const price=+$('price').value,down=+$('down').value,trade=+$('trade').value,r=+$('rate').value/100/12,n=+$('term').value;const loan=price-down-trade;const mp=loan*(r*Math.pow(1+r,n))/(Math.pow(1+r,n)-1);const total=mp*n;const interest=total-loan;$('out').innerHTML='<div class="stat"><div class="val" style="font-size:1.5rem;color:var(--a)">$'+fmt(mp)+'</div><div class="lbl">Monthly Payment</div></div><div class="stat"><div class="val">$'+fmt(loan,0)+'</div><div class="lbl">Loan Amount</div></div><div class="stat"><div class="val">$'+fmt(interest,0)+'</div><div class="lbl">Total Interest</div></div><div class="stat"><div class="val">$'+fmt(total,0)+'</div><div class="lbl">Total Cost</div></div><div class="stat"><div class="val">'+fmt(interest/loan*100,1)+'%</div><div class="lbl">Interest/Principal</div></div><div class="stat"><div class="val">$'+fmt(price,0)+'</div><div class="lbl">Vehicle Price</div></div>'}`
    },
    { slug:'net-pay-calculator', title:'Net Pay Calculator (Take-Home Pay)', desc:'Calculate your take-home pay after federal tax, state tax, Social Security, and Medicare deductions.',
      keywords:'net pay calculator, take home pay, paycheck calculator, salary after tax, income tax calculator',
      html:`<div class="row"><div class="field"><label class="label">Annual Salary ($)</label><input type="number" id="salary" value="75000"></div><div class="field"><label class="label">Pay Frequency</label><select id="freq"><option value="26" selected>Bi-weekly</option><option value="24">Semi-monthly</option><option value="52">Weekly</option><option value="12">Monthly</option></select></div></div>
<div class="row"><div class="field"><label class="label">Filing Status</label><select id="filing"><option value="single" selected>Single</option><option value="married">Married Filing Jointly</option><option value="head">Head of Household</option></select></div><div class="field"><label class="label">State Tax Rate (%)</label><input type="number" id="state" value="5" step="0.1"></div></div>
<div class="field"><label class="label">Pre-tax Deductions (401k, HSA, etc.) per pay period ($)</label><input type="number" id="pretax" value="0"></div>
<button class="btn" onclick="calc()">Calculate</button><div class="results-grid" id="out"></div>`,
      js:`function calc(){const salary=+$('salary').value,freq=+$('freq').value,stateRate=+$('state').value/100,pretax=+$('pretax').value;const annualPretax=pretax*freq;const taxable=salary-annualPretax;const brackets=[{r:.1,min:0,max:11600},{r:.12,min:11600,max:47150},{r:.22,min:47150,max:100525},{r:.24,min:100525,max:191950},{r:.32,min:191950,max:243725},{r:.35,min:243725,max:609350},{r:.37,min:609350,max:Infinity}];let fedTax=0;for(const b of brackets){if(taxable>b.min){fedTax+=(Math.min(taxable,b.max)-b.min)*b.r}}const ss=Math.min(salary,168600)*0.062;const medicare=salary*0.0145;const stateTax=taxable*stateRate;const totalTax=fedTax+ss+medicare+stateTax;const netAnnual=salary-totalTax-annualPretax;const netPer=netAnnual/freq;$('out').innerHTML='<div class="stat"><div class="val" style="font-size:1.5rem;color:#22c55e">$'+fmt(netPer)+'</div><div class="lbl">Take-Home Per Paycheck</div></div><div class="stat"><div class="val">$'+fmt(netAnnual,0)+'</div><div class="lbl">Annual Take-Home</div></div><div class="stat"><div class="val">$'+fmt(fedTax/freq)+'</div><div class="lbl">Federal Tax</div></div><div class="stat"><div class="val">$'+fmt(stateTax/freq)+'</div><div class="lbl">State Tax</div></div><div class="stat"><div class="val">$'+fmt(ss/freq)+'</div><div class="lbl">Social Security</div></div><div class="stat"><div class="val">$'+fmt(medicare/freq)+'</div><div class="lbl">Medicare</div></div><div class="stat"><div class="val">'+fmt(totalTax/salary*100,1)+'%</div><div class="lbl">Effective Tax Rate</div></div><div class="stat"><div class="val">$'+fmt(totalTax,0)+'</div><div class="lbl">Total Annual Taxes</div></div>'}`
    },
    { slug:'concrete-calculator', title:'Concrete Calculator', desc:'Calculate how much concrete you need in cubic yards. Enter dimensions for slabs, walls, columns, and footings.',
      keywords:'concrete calculator, how much concrete, cubic yards, concrete slab, concrete estimator',
      html:`<div class="field"><label class="label">Shape</label><select id="shape" onchange="toggleShape()"><option value="slab">Slab / Square Footing</option><option value="cylinder">Cylinder / Round Column</option><option value="wall">Wall / Continuous Footing</option></select></div>
<div id="slabFields"><div class="row3"><div class="field"><label class="label">Length (ft)</label><input type="number" id="length" value="20"></div><div class="field"><label class="label">Width (ft)</label><input type="number" id="width" value="20"></div><div class="field"><label class="label">Depth (in)</label><input type="number" id="depth" value="4"></div></div></div>
<div id="cylFields" style="display:none"><div class="row3"><div class="field"><label class="label">Diameter (in)</label><input type="number" id="diam" value="12"></div><div class="field"><label class="label">Height (ft)</label><input type="number" id="cheight" value="4"></div><div class="field"><label class="label">Quantity</label><input type="number" id="qty" value="4"></div></div></div>
<button class="btn" onclick="calc()">Calculate</button><div class="results-grid" id="out"></div>`,
      js:`function toggleShape(){const s=$('shape').value;$('slabFields').style.display=s==='cylinder'?'none':'';$('cylFields').style.display=s==='cylinder'?'':'none'}function calc(){const s=$('shape').value;let cuFt;if(s==='cylinder'){const r=+$('diam').value/2/12;const h=+$('cheight').value;const q=+$('qty').value;cuFt=Math.PI*r*r*h*q}else{cuFt=+$('length').value*+$('width').value*(+$('depth').value/12)}const cuYd=cuFt/27;const bags60=Math.ceil(cuYd*27/0.45);const bags80=Math.ceil(cuYd*27/0.6);$('out').innerHTML='<div class="stat"><div class="val" style="font-size:1.8rem;color:var(--a)">'+fmt(cuYd,2)+'</div><div class="lbl">Cubic Yards</div></div><div class="stat"><div class="val">'+fmt(cuFt,1)+'</div><div class="lbl">Cubic Feet</div></div><div class="stat"><div class="val">'+bags60+'</div><div class="lbl">60-lb Bags</div></div><div class="stat"><div class="val">'+bags80+'</div><div class="lbl">80-lb Bags</div></div><div class="stat"><div class="val">~$'+fmt(cuYd*150,0)+'</div><div class="lbl">Est. Cost (delivered)</div></div><div class="stat"><div class="val">+10%</div><div class="lbl">Order Extra for Waste</div></div>'}`
    },
    { slug:'bac-calculator', title:'Blood Alcohol Content (BAC) Calculator', desc:'Estimate your blood alcohol level based on drinks consumed, body weight, and time. Know when you are safe to drive.',
      keywords:'BAC calculator, blood alcohol calculator, drunk calculator, alcohol calculator, how many drinks',
      html:`<div class="row"><div class="field"><label class="label">Your Weight (lbs)</label><input type="number" id="weight" value="180"></div><div class="field"><label class="label">Gender</label><select id="gender"><option value="male">Male</option><option value="female">Female</option></select></div></div>
<div class="row"><div class="field"><label class="label">Number of Drinks</label><input type="number" id="drinks" value="3" step="0.5"></div><div class="field"><label class="label">Hours Drinking</label><input type="number" id="hours" value="2" step="0.5"></div></div>
<p style="font-size:.75rem;color:var(--m);margin-bottom:1rem">1 drink = 12oz beer (5%) = 5oz wine (12%) = 1.5oz spirits (40%)</p>
<button class="btn" onclick="calc()">Estimate BAC</button><div class="results-grid" id="out"></div>`,
      js:`function calc(){const w=+$('weight').value,g=$('gender').value,d=+$('drinks').value,h=+$('hours').value;const r=g==='male'?0.68:0.55;const bac=(d*0.6*5.14)/(w*r)-0.015*h;const level=Math.max(0,bac);const status=level<0.02?'🟢 Sober':level<0.04?'🟡 Minimal':level<0.08?'🟠 Impaired':level<0.15?'🔴 Legally Drunk':'🚨 Dangerous';const drive=level<0.08?'✅ Under legal limit':'❌ Over legal limit (0.08)';const soberIn=level>0?fmt(level/0.015,1)+' hours':'Now';$('out').innerHTML='<div class="stat"><div class="val" style="font-size:2rem;color:'+(level<0.08?'#22c55e':'#ef4444')+'">'+fmt(level,3)+'%</div><div class="lbl">Estimated BAC</div></div><div class="stat"><div class="val">'+status+'</div><div class="lbl">Impairment Level</div></div><div class="stat"><div class="val">'+drive+'</div><div class="lbl">Legal to Drive?</div></div><div class="stat"><div class="val">~'+soberIn+'</div><div class="lbl">Time to Sober</div></div>';$('out').innerHTML+='<div style="grid-column:1/-1;text-align:center;padding:.75rem;background:var(--s);border-radius:8px;margin-top:.5rem;font-size:.8rem;color:var(--m)">⚠️ This is an estimate only. Many factors affect BAC. Never drink and drive.</div>'}`
    },
    { slug:'sleep-calculator', title:'Sleep Calculator', desc:'Find the best time to wake up or go to sleep based on sleep cycles. Wake up feeling refreshed, not groggy.',
      keywords:'sleep calculator, sleep cycle, when to wake up, when to go to sleep, sleep schedule, REM cycle',
      html:`<div class="field"><label class="label">I want to...</label><select id="mode" onchange="toggleMode()"><option value="wake">Calculate when to WAKE UP (I know my bedtime)</option><option value="sleep">Calculate when to SLEEP (I know my wake time)</option></select></div>
<div id="wakeMode"><div class="field"><label class="label">I plan to fall asleep at:</label><div class="row"><select id="bedH" style="width:auto"><option value="20">8 PM</option><option value="21">9 PM</option><option value="22" selected>10 PM</option><option value="23">11 PM</option><option value="0">12 AM</option><option value="1">1 AM</option></select><select id="bedM" style="width:auto"><option value="0" selected>:00</option><option value="15">:15</option><option value="30">:30</option><option value="45">:45</option></select></div></div></div>
<div id="sleepMode" style="display:none"><div class="field"><label class="label">I need to wake up at:</label><div class="row"><select id="wakeH" style="width:auto"><option value="5">5 AM</option><option value="6" selected>6 AM</option><option value="7">7 AM</option><option value="8">8 AM</option><option value="9">9 AM</option></select><select id="wakeM" style="width:auto"><option value="0" selected>:00</option><option value="15">:15</option><option value="30">:30</option><option value="45">:45</option></select></div></div></div>
<button class="btn" onclick="calc()">Calculate Sleep Times</button><div id="out" style="margin-top:1.5rem"></div>`,
      js:`function toggleMode(){$('wakeMode').style.display=$('mode').value==='wake'?'':'none';$('sleepMode').style.display=$('mode').value==='sleep'?'':'none'}function calc(){const cycle=90;const fallAsleep=15;if($('mode').value==='wake'){const h=+$('bedH').value,m=+$('bedM').value;const bed=h*60+m+fallAsleep;let html='<div style="text-align:center;margin-bottom:1rem"><div style="font-size:.85rem;color:var(--m)">If you fall asleep at '+(h>12?h-12:h||12)+':'+(m<10?'0':'')+m+(h>=12?' PM':' AM')+', wake up at:</div></div><div class="results-grid">';for(let c=6;c>=3;c--){const wake=(bed+c*cycle)%1440;const wh=Math.floor(wake/60);const wm=wake%60;const quality=c>=5?'🟢 Ideal':c===4?'🟡 OK':'🟠 Short';html+='<div class="stat"><div class="val" style="color:'+(c>=5?'#22c55e':c===4?'#eab308':'#ef4444')+'">'+(wh>12?wh-12:wh||12)+':'+(wm<10?'0':'')+wm+(wh>=12?' PM':' AM')+'</div><div class="lbl">'+c+' cycles ('+c*1.5+'h) '+quality+'</div></div>'}html+='</div>';$('out').innerHTML=html}else{const h=+$('wakeH').value,m=+$('wakeM').value;const wake=h*60+m;let html='<div style="text-align:center;margin-bottom:1rem"><div style="font-size:.85rem;color:var(--m)">To wake at '+h+':'+(m<10?'0':'')+m+' AM, go to bed at:</div></div><div class="results-grid">';for(let c=6;c>=3;c--){let sleep=(wake-c*cycle-fallAsleep+1440)%1440;const sh=Math.floor(sleep/60);const sm=sleep%60;const quality=c>=5?'🟢 Ideal':c===4?'🟡 OK':'🟠 Short';html+='<div class="stat"><div class="val" style="color:'+(c>=5?'#22c55e':c===4?'#eab308':'#ef4444')+'">'+(sh>12?sh-12:sh||12)+':'+(sm<10?'0':'')+sm+(sh>=12?' PM':' AM')+'</div><div class="lbl">'+c+' cycles ('+c*1.5+'h) '+quality+'</div></div>'}html+='</div>';$('out').innerHTML=html}}`
    },
    { slug:'pace-calculator', title:'Running Pace Calculator', desc:'Calculate your running pace, speed, and finish time. Convert between pace per mile and pace per kilometer.',
      keywords:'pace calculator, running pace, marathon pace, 5k pace, running speed, mile pace calculator',
      html:`<div class="field"><label class="label">Calculate</label><select id="mode" onchange="toggleMode()"><option value="pace">Pace from Distance + Time</option><option value="time">Finish Time from Distance + Pace</option><option value="distance">Distance from Time + Pace</option></select></div>
<div class="row"><div class="field"><label class="label">Distance</label><div class="row"><input type="number" id="dist" value="5" step="0.1" style="width:60%"><select id="dunit" style="width:38%"><option value="km" selected>km</option><option value="mi">miles</option></select></div></div><div class="field"><label class="label">Time</label><div class="row3"><input type="number" id="th" value="0" min="0" placeholder="h" style="width:30%"><input type="number" id="tm" value="25" min="0" max="59" placeholder="m" style="width:30%"><input type="number" id="ts" value="0" min="0" max="59" placeholder="s" style="width:30%"></div></div></div>
<button class="btn" onclick="calc()">Calculate</button><div class="results-grid" id="out"></div>`,
      js:`function toggleMode(){}function calc(){const dist=+$('dist').value*(($('dunit').value==='mi')?1.60934:1);const totalSec=+$('th').value*3600+ +$('tm').value*60+ +$('ts').value;const paceSecKm=totalSec/dist;const paceSecMi=paceSecKm*1.60934;const speedKmh=dist/(totalSec/3600);const speedMph=speedKmh/1.60934;const pm=Math.floor(paceSecKm/60);const ps=Math.round(paceSecKm%60);const pmm=Math.floor(paceSecMi/60);const pms=Math.round(paceSecMi%60);const races=[['5K',5],['10K',10],['Half Marathon',21.0975],['Marathon',42.195]];let raceHtml=races.map(([name,d])=>{const t=paceSecKm*d;const h=Math.floor(t/3600);const m=Math.floor((t%3600)/60);const s=Math.round(t%60);return'<div class="stat"><div class="val">'+(h?h+':':'')+String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')+'</div><div class="lbl">'+name+'</div></div>'}).join('');$('out').innerHTML='<div class="stat"><div class="val" style="color:var(--a)">'+pm+':'+String(ps).padStart(2,'0')+'</div><div class="lbl">Pace /km</div></div><div class="stat"><div class="val">'+pmm+':'+String(pms).padStart(2,'0')+'</div><div class="lbl">Pace /mile</div></div><div class="stat"><div class="val">'+fmt(speedKmh,1)+'</div><div class="lbl">km/h</div></div><div class="stat"><div class="val">'+fmt(speedMph,1)+'</div><div class="lbl">mph</div></div>'+raceHtml}`
    },
    { slug:'screen-size-calculator', title:'Screen Size Calculator', desc:'Calculate display dimensions from diagonal size and aspect ratio. Compare TV, monitor, and phone screen sizes.',
      keywords:'screen size calculator, TV size calculator, monitor dimensions, display size, aspect ratio calculator',
      html:`<div class="row"><div class="field"><label class="label">Diagonal Size (inches)</label><input type="number" id="diag" value="55" step="0.1"></div><div class="field"><label class="label">Aspect Ratio</label><select id="ratio"><option value="16:9" selected>16:9 (Standard TV/Monitor)</option><option value="21:9">21:9 (Ultrawide)</option><option value="16:10">16:10 (MacBook)</option><option value="4:3">4:3 (Classic)</option><option value="3:2">3:2 (Surface)</option></select></div></div>
<button class="btn" onclick="calc()">Calculate</button><div class="results-grid" id="out"></div>`,
      js:`function calc(){const d=+$('diag').value;const[rw,rh]=$('ratio').value.split(':').map(Number);const angle=Math.atan(rh/rw);const h=d*Math.sin(angle);const w=d*Math.cos(angle);const area=w*h;$('out').innerHTML='<div class="stat"><div class="val" style="color:var(--a)">'+fmt(w,1)+'"</div><div class="lbl">Width</div></div><div class="stat"><div class="val">'+fmt(h,1)+'"</div><div class="lbl">Height</div></div><div class="stat"><div class="val">'+fmt(w*2.54,1)+' cm</div><div class="lbl">Width (metric)</div></div><div class="stat"><div class="val">'+fmt(h*2.54,1)+' cm</div><div class="lbl">Height (metric)</div></div><div class="stat"><div class="val">'+fmt(area,0)+' in²</div><div class="lbl">Screen Area</div></div><div class="stat"><div class="val">'+fmt(d,1)+'"</div><div class="lbl">Diagonal</div></div>'}`
    },
    { slug:'hex-to-rgb', title:'HEX to RGB Color Converter', desc:'Convert HEX color codes to RGB values and vice versa. Preview colors and copy CSS code.',
      keywords:'hex to rgb, rgb to hex, color converter, color picker, css color, html color codes',
      html:`<div class="row"><div class="field"><label class="label">HEX Color</label><input type="text" id="hex" value="#6366F1" oninput="fromHex()" maxlength="7"></div><div class="field"><label class="label">Preview</label><div id="preview" style="height:44px;border-radius:8px;background:#6366F1;border:1px solid var(--b)"></div></div></div>
<div class="row3"><div class="field"><label class="label">R</label><input type="number" id="r" value="99" min="0" max="255" oninput="fromRgb()"></div><div class="field"><label class="label">G</label><input type="number" id="g" value="102" min="0" max="255" oninput="fromRgb()"></div><div class="field"><label class="label">B</label><input type="number" id="b" value="241" min="0" max="255" oninput="fromRgb()"></div></div>
<div class="results-grid" id="out"></div>`,
      js:`function fromHex(){const h=$('hex').value.replace('#','');if(h.length===6){const r=parseInt(h.substr(0,2),16),g=parseInt(h.substr(2,2),16),b=parseInt(h.substr(4,2),16);$('r').value=r;$('g').value=g;$('b').value=b;update(r,g,b)}}function fromRgb(){const r=+$('r').value,g=+$('g').value,b=+$('b').value;$('hex').value='#'+[r,g,b].map(x=>x.toString(16).padStart(2,'0')).join('');update(r,g,b)}function update(r,g,b){const hex=$('hex').value;$('preview').style.background=hex;const hsl=rgbToHsl(r,g,b);$('out').innerHTML='<div class="stat"><div class="val" style="font-size:.9rem">'+hex+'</div><div class="lbl">HEX</div></div><div class="stat"><div class="val" style="font-size:.9rem">rgb('+r+', '+g+', '+b+')</div><div class="lbl">RGB</div></div><div class="stat"><div class="val" style="font-size:.9rem">hsl('+hsl[0]+', '+hsl[1]+'%, '+hsl[2]+'%)</div><div class="lbl">HSL</div></div><div class="stat"><div class="val"><button onclick="navigator.clipboard.writeText(\\''+hex+'\\');this.textContent=\\'✓\\'" style="background:var(--a);color:#fff;border:none;padding:.3rem .8rem;border-radius:6px;cursor:pointer">Copy HEX</button></div><div class="lbl">&nbsp;</div></div>'}function rgbToHsl(r,g,b){r/=255;g/=255;b/=255;const max=Math.max(r,g,b),min=Math.min(r,g,b);let h,s,l=(max+min)/2;if(max===min){h=s=0}else{const d=max-min;s=l>0.5?d/(2-max-min):d/(max+min);switch(max){case r:h=((g-b)/d+(g<b?6:0))/6;break;case g:h=((b-r)/d+2)/6;break;case b:h=((r-g)/d+4)/6;break}}return[Math.round(h*360),Math.round(s*100),Math.round(l*100)]}fromHex()`
    },
];

console.log('Generating '+calcs.length+' calculator pages (batch 3)...');
let sitemapEntries = [];

calcs.forEach(c => {
    const html = calcPage(c.slug, c.title, c.desc, c.keywords, c.html, c.js);
    fs.writeFileSync(__dirname + '/calc/' + c.slug + '.html', html);
    sitemapEntries.push('    <url><loc>' + BASE + '/calc/' + c.slug + '.html</loc><changefreq>monthly</changefreq><priority>0.8</priority></url>');
    console.log('  ✅ ' + c.slug);
});

// Update sitemap
const sitemap = fs.readFileSync(__dirname + '/sitemap.xml', 'utf8');
fs.writeFileSync(__dirname + '/sitemap.xml', sitemap.replace('</urlset>', sitemapEntries.join('\n') + '\n</urlset>'));

console.log('\n🎉 Generated ' + calcs.length + ' new calculators');
console.log('📊 Sitemap updated');
